# Site settings
title: My awesome Blog title
email: your-email@domain.com
description: "My awesome Blog powered by MiniSoda."
baseurl: ""
url: "http://yourdomain.com"

# Build settings
markdown: kramdown
kramdown:
  input: GFM
permalink: :title

# Syntax highlighting code.
highlight: true

sass:
   sass_dir: sass
   style: :compressed
   
# Preview server settings.
host: 127.0.0.1
port: 5000

# Social networks.
github:
bitbucket:
google:
twitter: