# Site settings

# site title
title: My awesome Blog title

# tagline (short intro)
tagline: A blogging framework for artisans

# description (meta description indexed my search engine bots)
description: A blogging framework for artisans.

# keywords used by users to find your website through search engines (example: awesome, website, minisoda
keywords: 

# if you website is deployed in a sub-folder change the attribute
baseurl: ""

# domain (your website url
url: "http://yodomain.com"

# The url adressing of your website http://yodomain.com/post/my-awesome-mini-soda-blog/
permalink: /post/:title

# Permalink to pages
paginate_path: "/page/:num"

# Number of post displayed per page
paginate: 4

# RSS/Atom feed
subscribe: /atom.xml

# Author name and email config
author:
  name:
  email: 

# Markdown Interpreter settings
markdown: kramdown
markdown_ext:  markdown,mkdown,mkdn,mkd,md
kramdown:
  input: GFM


# Syntax highlighting code
highlight: true

# website source folder
source: content

# website compiled output folder
destination: _deploy


jekyll-press:
  exclude: 'robots.txt' # Exclude files from processing - file name, glob pattern or array of file names and glob patterns
  js_options: {}      # js minifier options
  css_options: {}     # css minifier options
  html_options: {}    # html minifier options

# Sass
sass:
  sass_dir: styles
  style: :compressed

# File that don't need to be processed.
exclude: [
    'Gemfile',
    'Gemfile.lock'
]


# Webserver settings.
host: 0.0.0.0
port: 3000

# Gems and Plugins
gems:
- jekyll-sitemap
- jekyll-press
- jekyll-gist
- jemoji

# 3rd Party plugins foler
plugins: addons

# Social networks.
twitter: 
google: 
github:
bitbucket:
disqus:

# Webmaster settings.
google_site_verification:
bing_site_verification:

# Google Analytics
google_analytics_id: