# Site settings
title: My awesome Blog title
email: your-email@domain.com
description: "My awesome Blog powered by MiniSoda."
baseurl: ""
url: "http://yourdomain.com"

# Build settings
markdown: kramdown
kramdown:
  input: GFM
permalink: :title

# Syntax highlighting code.
highlight: true

sass:
    sass_dir: sass
    style: :compressed

# Gems and Apps.
gems:
- jekyll-sitemap
- jekyll-gist
plugins: apps
   
# Preview server settings.
host: 0.0.0.0
port: 3000

# Social networks.
github:
bitbucket:
google:
twitter:

# Deployment.

# FTP.
ftp_host: ""
ftp_dir: ""
ftp_passive: false
ftp_post: 21
ftp_username: ""
ftp_password: ""