# Site settings
title: My awesome Blog title
subtitle: Powered by MiniSoda
author:
email: your-email@domain.com
description: "My awesome Blog powered by MiniSoda."
baseurl: ""
url: "http://yodomain.com"
search_bar: https://google.com/search

# RSS feed
subscribe: /atom.xml


# Markdown settings
markdown: kramdown
kramdown:
  input: GFM

# Example http://yodomain.com/my-awesome-mini-soda-blog/
permalink: :title

# Syntax highlighting code
highlight: true

# Blog source folder
source: source
# Blog compiled folder
destination: _deploy

# Sass
sass:
  sass_dir: styles
  style: :compressed

# Gems and Apps.
gems:
- jekyll-sitemap
- jekyll-gist

plugins: apps

# Preview server settings.
host: 0.0.0.0
port: 3000

# Social networks.
github:
bitbucket:
google:
twitter:
disqus:

# Disqus comments switch true/false
comments: false

# Deployment.

# FTP.
ftp_host: ""
ftp_dir: ""
ftp_passive: false
ftp_post: 21
ftp_username: ""
ftp_password: ""
