# Site settings
title: My awesome Blog title
tagline: A blogging framework for artisan
description: A blogging framework for artisan.
author:
baseurl: ""
url: "http://yodomain.com"

# Example http://yodomain.com/my-awesome-mini-soda-blog/
permalink: :title
# Limit post per page
paginate: 8

# RSS feed
subscribe: /atom.xml

# Author
author:
  name:
  email: your-email@domain.com

# Markdown Interpreter settings
markdown: kramdown
markdown_ext:  markdown,mkdown,mkdn,mkd,md
kramdown:
  input: GFM


# Syntax highlighting code
highlight: true

# Blog source folder
source: _content
# Blog compiled folder
destination: _deploy

# Sass
sass:
  sass_dir: styles
  style: :compressed

exclude: [styles/includes]


# Preview server settings.
host: 0.0.0.0
port: 3000

# Gems and Apps.
gems:
- jekyll-sitemap
- jekyll-gist

plugins: apps

# Social networks.
twitter: 
google: 
github:
bitbucket:
disqus:

# Webmaster settings.
google_site_verification:


# Deployment.

# FTP.
ftp_host: ""
ftp_dir: ""
ftp_passive: false
ftp_post: 21
ftp_username: ""
ftp_password: ""
