source 'https://rubygems.org'

gem 'jekyll'
gem 'jekyll-sitemap'
gem 'jekyll-watch'
gem 'jekyll-sass-converter'
gem 'jekyll-coffeescript'
gem 'jekyll-paginate'
gem 'jekyll-gist'
gem 'liquid'
gem 'kramdown'
gem 'pygments.rb'
gem 'sass'
gem 'glynn'
